//
//  MovieDetailsInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/3/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic {
  func verifyAndSendMovie(request: MovieDetails.ShowDetails.Request)
}

protocol MovieDetailsDataStore {
  var movie: MovieObject? { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore {
  var presenter: MovieDetailsPresentationLogic?
  
  var movie: MovieObject?
  
  // MARK: Prepare
  
  func verifyAndSendMovie(request: MovieDetails.ShowDetails.Request) {
    guard let movie = movie else { return }
    
    let response = MovieDetails.ShowDetails.Response(movie: movie)
    presenter?.displayMovie(response: response)
  }
}
