//
//  MovieDetailsRouter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/3/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieDetailsRoutingLogic {
  func routeToShowMovieReviews(segue: UIStoryboardSegue?)
}

protocol MovieDetailsDataPassing {
  var dataStore: MovieDetailsDataStore? { get }
}

class MovieDetailsRouter: NSObject, MovieDetailsRoutingLogic, MovieDetailsDataPassing {
  weak var viewController: MovieDetailsViewController?
  var dataStore: MovieDetailsDataStore?
  
  // MARK: Routing
  
  func routeToShowMovieReviews(segue: UIStoryboardSegue?) {
    
    guard let destinationVC = segue?.destination as? MovieReviewsViewController,
      var destinationDS = destinationVC.router?.dataStore,
      let dataStore = self.dataStore else { return }
    
    passDataToMovieReviews(source: dataStore, destination: &destinationDS)
  }
  
  // MARK: Passing data
  
  func passDataToMovieReviews(source: MovieDetailsDataStore, destination: inout MovieReviewsDataStore) {
    destination.movie = source.movie
  }
}
