//
//  WatchListWorker.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/28/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchListWorkerType {
  func getSavedMovies(completionHandler: @escaping MoviesResult)
}

class WatchListWorker: WatchListWorkerType {
  
  // MARK: - Dependencies
  
  // MARK: - Init
  
  // MARK: - Methods
  
  func getSavedMovies(completionHandler: @escaping MoviesResult) {
    
    MoviesWorker.shared.fetchMovies(forPage: nil) { (movies, error) in
      guard error == nil else {
        completionHandler([], error!)
        print("ERROR: Error attempting to retrieve movies from Realm.")
        return
      }
      completionHandler(movies, nil)
    }
  }
}
