//
//  SearchAllInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 1/8/18.
//  Copyright (c) 2018 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchStatus {
  case success
  case failure
}

protocol SearchAllBusinessLogic {
  func search(for request: SearchAll.Search.Request)
}

protocol SearchAllDataStore {
  var movies: [Movie]? { get set }
}

class SearchAllInteractor: SearchAllBusinessLogic, SearchAllDataStore {
  var presenter: SearchAllPresentationLogic?
  var movies: [Movie]?
  
  // MARK: Do something
  
  func search(for request: SearchAll.Search.Request) {
    let searchService = APISearchService()
    let searchWorker = SearchWorker(searchService: searchService)
    
    searchWorker.search(query: request.query) { [weak self] results, error in
      guard error == nil else {
        return
      }
      
      self?.movies = results
      
      let response = SearchAll.Search.Response(results: results)
      self?.presenter?.presentResults(response: response)
    }
  }
}
