//
//  SearchAllInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 1/8/18.
//  Copyright (c) 2018 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchAllBusinessLogic {
  func doSomething(request: SearchAll.Something.Request)
}

protocol SearchAllDataStore {
  //var name: String { get set }
}

class SearchAllInteractor: SearchAllBusinessLogic, SearchAllDataStore {
  var presenter: SearchAllPresentationLogic?
  var worker: SearchAllWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SearchAll.Something.Request) {
    worker = SearchAllWorker()
    worker?.doSomeWork()
    
    let response = SearchAll.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
