//
//  SearchAllPresenter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 1/8/18.
//  Copyright (c) 2018 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchAllPresentationLogic {
  func presentResults(response: SearchAll.Search.Response)
}

class SearchAllPresenter: SearchAllPresentationLogic {
  weak var viewController: SearchAllDisplayLogic?
  
  // MARK: Do something
  
  func presentResults(response: SearchAll.Search.Response) {
    let viewModel = SearchAll.Search.ViewModel(movies: response.results)
    viewController?.displayResults(viewModel: viewModel)
  }
}
