//
//  SearchResultsPresenter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 1/9/18.
//  Copyright (c) 2018 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultsPresentationLogic {
  func presentSomething(response: SearchResults.Something.Response)
}

class SearchResultsPresenter: SearchResultsPresentationLogic {
  weak var viewController: SearchResultsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SearchResults.Something.Response) {
    let viewModel = SearchResults.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
