//
//  SearchResultsInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 1/9/18.
//  Copyright (c) 2018 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultsBusinessLogic {
  func doSomething(request: SearchResults.Something.Request)
}

protocol SearchResultsDataStore {
  var movies: [Movie]? { get set }
}

class SearchResultsInteractor: SearchResultsBusinessLogic, SearchResultsDataStore {
  var presenter: SearchResultsPresentationLogic?
  var movies: [Movie]?
  
  // MARK: Do something
  
  func doSomething(request: SearchResults.Something.Request) {
    
    let response = SearchResults.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
