//
//  MovieReviewsRouter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/11/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieReviewsRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol MovieReviewsDataPassing {
  var dataStore: MovieReviewsDataStore? { get }
}

class MovieReviewsRouter: NSObject, MovieReviewsRoutingLogic, MovieReviewsDataPassing {
  weak var viewController: MovieReviewsViewController?
  var dataStore: MovieReviewsDataStore?
  
  //   MARK: Routing
  //
  //   MARK: Navigation
  //
  //   MARK: Passing data
  
}
