//
//  MovieReviewsInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/11/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieReviewsBusinessLogic {
  func fetchReviews(request: MovieReviews.GetReviews.Request)
}

protocol MovieReviewsDataStore {
  var movie: MovieObject? { get set }
  var reviews: [ReviewObject]? { get set }
}

class MovieReviewsInteractor: MovieReviewsBusinessLogic, MovieReviewsDataStore {
  var presenter: MovieReviewsPresentationLogic?
  
  var movie: MovieObject?
  var reviews: [ReviewObject]?
  
  // MARK: Fetch Reviews
  
  func fetchReviews(request: MovieReviews.GetReviews.Request) {
    guard let movie = movie else { return }
    
    MoviesWorker.shared.fetchReviews(forMovie: movie) { (reviews, error) in
      guard error == nil else {
        print("Error occurred while retrieving reviews for \(movie.title)")
        return
      }
      
      self.reviews = reviews
      
      let response = MovieReviews.GetReviews.Response(reviews: reviews)
      self.presenter?.presentReviews(response: response)
      
    }
    
    
  }
}
