//
//  ListMoviesRouter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 10/30/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListMoviesRoutingLogic {
  func routeToShowMovieDetails(segue: UIStoryboardSegue?)
}

protocol ListMoviesDataPassing {
  var dataStore: ListMoviesDataStore? { get }
}

class ListMoviesRouter: NSObject, ListMoviesRoutingLogic, ListMoviesDataPassing {
  weak var viewController: ListMoviesViewController?
  var dataStore: ListMoviesDataStore?
  
  // MARK: Routing
  
  func routeToShowMovieDetails(segue: UIStoryboardSegue?) {
    
    guard let destinationVC = segue?.destination as? MovieDetailsViewController,
      var destinationDS = destinationVC.router?.dataStore,
      let dataStore = self.dataStore else { return }
    
    passDataToShowMovieDetails(source: dataStore, destination: &destinationDS)
  }
  
  // MARK: Navigation
  
  //func navigateToSomewhere(source: ListMoviesViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  func passDataToShowMovieDetails(source: ListMoviesDataStore, destination: inout MovieDetailsDataStore) {
    guard let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row else { return }
    
    destination.movie = source.movies?[selectedRow]
  }
}
