//
//  ListMoviesModels.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 10/30/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListMovies {
  // MARK: Use cases
  
  enum FetchMovies {
    struct Request {
      var page: Int
    }
    struct Response {
      var movies: [Movie]
    }
    struct ViewModel {
      
      struct DisplayedMovie {
        var title: String
        var backdropImageURL: URL
      }
      
      var displayedMovies: [DisplayedMovie]
    }
  }
}
