//
//  ListMoviesPresenter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 10/30/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesPresentationLogic {
  func presentMovies(response: ListMovies.FetchMovies.Response)
}

class ListMoviesPresenter: ListMoviesPresentationLogic {
  
  weak var viewController: ListMoviesDisplayLogic?
  
  // MARK: Do something
  
  func presentMovies(response: ListMovies.FetchMovies.Response) {
    var displayedMovies = [ListMovies.FetchMovies.ViewModel.DisplayedMovie]()
    
    for movie in response.movies {
      let url = movie.getImageURL(forType: .backdrop)
      let displayedMovie = ListMovies.FetchMovies.ViewModel.DisplayedMovie(title: movie.title, averageScore: movie.voteAverage, backdropImageURL: url)
      displayedMovies.append(displayedMovie)
    }
    
    print("COUNTER: \(displayedMovies.count) MOVIES")
    
    let viewModel = ListMovies.FetchMovies.ViewModel(displayedMovies: displayedMovies)
    viewController?.displayMovies(viewModel: viewModel)
    
  }
}
