//
//  ListMoviesPresenter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 10/30/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesPresentationLogic
{
  func presentSomething(response: ListMovies.Something.Response)
}

class ListMoviesPresenter: ListMoviesPresentationLogic
{
  weak var viewController: ListMoviesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListMovies.Something.Response)
  {
    let viewModel = ListMovies.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
