//
//  WatchListPresenter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/27/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchListPresentationLogic {
  func presentSomething(response: WatchList.Something.Response)
}

class WatchListPresenter: WatchListPresentationLogic {
  
  // MARK: - Properties
  
  weak var viewController: WatchListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WatchList.Something.Response) {
    let viewModel = WatchList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
