//
//  WatchListInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/27/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchListBusinessLogic {
  func doSomething(request: WatchList.Something.Request)
}

protocol WatchListDataStore {
  //var name: String { get set }
}

class WatchListInteractor: WatchListBusinessLogic, WatchListDataStore {
  
  // MARK: - Dependencies
  
  var presenter: WatchListPresentationLogic?
  var worker: WatchListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WatchList.Something.Request) {
    worker = WatchListWorker()
    worker?.doSomeWork()
    
    let response = WatchList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
