//
//  WatchListModels.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/27/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WatchList {
  // MARK: Use cases
  
  enum Something {
    
    struct Request {
      
    }
    struct Response {
      
    }
    struct ViewModel {
      
    }
  }
}
