//
//  WatchListInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/27/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchListBusinessLogic {
  func loadMovies(request: WatchList.LoadMovies.Request)
}

protocol WatchListDataStore {
  //var name: String { get set }
}

class WatchListInteractor: WatchListBusinessLogic, WatchListDataStore {
  
  // MARK: - Dependencies
  
  var presenter: WatchListPresentationLogic?
  var worker = WatchListWorker()
  //var name: String = ""
  
  // MARK: Do something
  
  func loadMovies(request: WatchList.LoadMovies.Request) {
    worker.getSavedMovies { [weak self] (movies, error) in
      let response = WatchList.LoadMovies.Response(movies: movies)
      
      self?.presenter?.presentMovies(response: response)
    }
  }
}
