//
//  MovieDetailsInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/3/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic {
  func getMovie(request: MovieDetails.GetMovie.Request)
}

protocol MovieDetailsDataStore {
  var movie: MovieObject! { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore {
  var presenter: MovieDetailsPresentationLogic?
  var worker: MovieDetailsWorker?
  
  var movie: MovieObject!
  
  // MARK: Do something
  
  func getMovie(request: MovieDetails.GetMovie.Request) {
    worker = MovieDetailsWorker()
    worker?.doSomeWork()
    
    let response = MovieDetails.GetMovie.Response(movie: movie)
    presenter?.displayMovie(response: response)
  }
}
