//
//  MovieDetailsRouter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/3/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieDetailsRoutingLogic {
  func routeToShowMovieReviews(segue: UIStoryboardSegue?)
}

protocol MovieDetailsDataPassing {
  var dataStore: MovieDetailsDataStore? { get }
}

class MovieDetailsRouter: NSObject, MovieDetailsRoutingLogic, MovieDetailsDataPassing {
  weak var viewController: MovieDetailsViewController?
  var dataStore: MovieDetailsDataStore?
  
  // MARK: Routing
  
  func routeToShowMovieReviews(segue: UIStoryboardSegue?) {
    
    guard let destinationVC = segue?.destination as? MovieReviewsViewController,
      var destinationDS = destinationVC.router?.dataStore,
      let dataStore = self.dataStore else { return }
    
    passDataToMovieReviews(source: dataStore, destination: &destinationDS)
  }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}
  
  // MARK: Navigation
  
  //func navigateToSomewhere(source: MovieDetailsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  func passDataToMovieReviews(source: MovieDetailsDataStore, destination: inout MovieReviewsDataStore) {
    destination.movie = source.movie
  }
}
