//
//  MovieDetailsPresenter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/3/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsPresentationLogic {
  func displayMovie(response: MovieDetails.ShowDetails.Response)
}

class MovieDetailsPresenter: MovieDetailsPresentationLogic {
  weak var viewController: MovieDetailsDisplayLogic?
  
  // MARK: Do something
  
  func displayMovie(response: MovieDetails.ShowDetails.Response) {
    let movie = response.movie
    
    let backdropURL = movie.getImageURL(forType: .backdrop)
    let posterURL = movie.getImageURL(forType: .poster)
    
    let displayedMovie = MovieDetails.ShowDetails.ViewModel.DisplayedMovie(backdropImage: backdropURL, posterImage: posterURL, title: movie.title, averageScore: movie.voteAverage, summary: movie.summary)
    
    let viewModel = MovieDetails.ShowDetails.ViewModel(displayedMovie: displayedMovie)
    viewController?.displayMovie(viewModel: viewModel)
  }
}
