//
//  MovieDetailsModels.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/3/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetails {
  // MARK: Use cases
  
  enum GetMovie {
    struct Request {
      
    }
    struct Response {
      var movie: Movie
    }
    struct ViewModel {
      struct DisplayedMovie {
        var backdropImage: URL
        var posterImage: URL
        var title: String
        var averageScore: Double
        var summary: String
      }
      var displayedMovie: DisplayedMovie
    }
  }
}
