//
//  MovieReviewsPresenter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/11/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieReviewsPresentationLogic
{
  func presentSomething(response: MovieReviews.Something.Response)
}

class MovieReviewsPresenter: MovieReviewsPresentationLogic
{
  weak var viewController: MovieReviewsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MovieReviews.Something.Response)
  {
    let viewModel = MovieReviews.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
