//
//  MovieReviewsPresenter.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/11/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieReviewsPresentationLogic {
  func presentReviews(response: MovieReviews.GetReviews.Response)
}

class MovieReviewsPresenter: MovieReviewsPresentationLogic {
  weak var viewController: MovieReviewsDisplayLogic?
  
  // MARK: Do something
  
  func presentReviews(response: MovieReviews.GetReviews.Response) {
    var displayedReviews = [MovieReviews.GetReviews.ViewModel.DisplayedReview]()
    
    for review in response.reviews {
      let displayedReview = MovieReviews.GetReviews.ViewModel.DisplayedReview(
        id: review.id,
        author: review.author,
        content: review.content)
      displayedReviews.append(displayedReview)
    }
    
    let viewModel = MovieReviews.GetReviews.ViewModel(displayedReviews: displayedReviews)
    viewController?.displayReviews(viewModel: viewModel)
  }
}
