//
//  MovieReviewsInteractor.swift
//  CleanMovieDB
//
//  Created by Francis Breidenbach on 11/11/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieReviewsBusinessLogic {
  func doSomething(request: MovieReviews.Something.Request)
}

protocol MovieReviewsDataStore {
  //var name: String { get set }
}

class MovieReviewsInteractor: MovieReviewsBusinessLogic, MovieReviewsDataStore {
  var presenter: MovieReviewsPresentationLogic?
  var worker: MovieReviewsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MovieReviews.Something.Request) {
    worker = MovieReviewsWorker()
    worker?.doSomeWork()
    
    let response = MovieReviews.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
